
set encoding=utf-8
set visualbell
set showcmd
set wildmenu
set lazyredraw
set incsearch
set hlsearch 
nnoremap <leader><space> :nohlsearch<CR>
let mapleader=","

syntax on
set tabstop=4
set softtabstop=4
set expandtab
set number
set ruler
set showmatch
